# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapreduce.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\x12\tmapreduce\";\n\nWorkerInfo\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"A\n\tHeartbeat\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0e\n\x06status\x18\x03 \x01(\t\")\n\x11HeartbeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\" \n\x0bTaskRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"p\n\x0eTaskAssignment\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x12\n\ninput_data\x18\x03 \x01(\t\x12\x14\n\x0cpartition_id\x18\x04 \x01(\x05\x12\x10\n\x08has_task\x18\x05 \x01(\x08\"m\n\nTaskResult\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x13\n\x0boutput_data\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\"\x1f\n\x07TaskAck\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\x9d\x02\n\rMasterService\x12\x44\n\x0eRegisterWorker\x12\x15.mapreduce.WorkerInfo\x1a\x1b.mapreduce.RegisterResponse\x12\x43\n\rSendHeartbeat\x12\x14.mapreduce.Heartbeat\x1a\x1c.mapreduce.HeartbeatResponse\x12@\n\x0bRequestTask\x12\x16.mapreduce.TaskRequest\x1a\x19.mapreduce.TaskAssignment\x12?\n\x12ReportTaskComplete\x12\x15.mapreduce.TaskResult\x1a\x12.mapreduce.TaskAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WORKERINFO']._serialized_start=30
  _globals['_WORKERINFO']._serialized_end=89
  _globals['_REGISTERRESPONSE']._serialized_start=91
  _globals['_REGISTERRESPONSE']._serialized_end=143
  _globals['_HEARTBEAT']._serialized_start=145
  _globals['_HEARTBEAT']._serialized_end=210
  _globals['_HEARTBEATRESPONSE']._serialized_start=212
  _globals['_HEARTBEATRESPONSE']._serialized_end=253
  _globals['_TASKREQUEST']._serialized_start=255
  _globals['_TASKREQUEST']._serialized_end=287
  _globals['_TASKASSIGNMENT']._serialized_start=289
  _globals['_TASKASSIGNMENT']._serialized_end=401
  _globals['_TASKRESULT']._serialized_start=403
  _globals['_TASKRESULT']._serialized_end=512
  _globals['_TASKACK']._serialized_start=514
  _globals['_TASKACK']._serialized_end=545
  _globals['_MASTERSERVICE']._serialized_start=548
  _globals['_MASTERSERVICE']._serialized_end=833
# @@protoc_insertion_point(module_scope)
